/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_qsys_0' in SOPC Builder design 'nios_test'
 * SOPC Builder design path: ../../nios_test.sopcinfo
 *
 * Generated: Fri Sep 29 12:31:23 MSD 2017
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00021820
#define ALT_CPU_CPU_FREQ 75000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x12
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 2048
#define ALT_CPU_EXCEPTION_ADDR 0x00010020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 75000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0x12
#define ALT_CPU_NAME "nios2_qsys_0"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_RESET_ADDR 0x00021000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00021820
#define NIOS2_CPU_FREQ 75000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x12
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 2048
#define NIOS2_EXCEPTION_ADDR 0x00010020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0x12
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_RESET_ADDR 0x00021000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_EPCS_FLASH_CONTROLLER
#define __ALTERA_AVALON_FIFO
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_AVALON_TIMER
#define __ALTERA_AVALON_UART
#define __ALTERA_ETH_TSE
#define __ALTERA_NIOS2_QSYS
#define __ALT_MM_SLAVE


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone III"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x22db8
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x22db8
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x22db8
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "nios_test"


/*
 * alt_mm_slave_0 configuration
 *
 */

#define ALT_MM_SLAVE_0_BASE 0x22000
#define ALT_MM_SLAVE_0_IRQ -1
#define ALT_MM_SLAVE_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ALT_MM_SLAVE_0_NAME "/dev/alt_mm_slave_0"
#define ALT_MM_SLAVE_0_SPAN 1024
#define ALT_MM_SLAVE_0_TYPE "alt_mm_slave"
#define ALT_MODULE_CLASS_alt_mm_slave_0 alt_mm_slave


/*
 * alt_mm_slave_1 configuration
 *
 */

#define ALT_MM_SLAVE_1_BASE 0x22400
#define ALT_MM_SLAVE_1_IRQ -1
#define ALT_MM_SLAVE_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ALT_MM_SLAVE_1_NAME "/dev/alt_mm_slave_1"
#define ALT_MM_SLAVE_1_SPAN 1024
#define ALT_MM_SLAVE_1_TYPE "alt_mm_slave"
#define ALT_MODULE_CLASS_alt_mm_slave_1 alt_mm_slave


/*
 * epcs_flash_controller_0 configuration
 *
 */

#define ALT_MODULE_CLASS_epcs_flash_controller_0 altera_avalon_epcs_flash_controller
#define EPCS_FLASH_CONTROLLER_0_BASE 0x21000
#define EPCS_FLASH_CONTROLLER_0_IRQ 1
#define EPCS_FLASH_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define EPCS_FLASH_CONTROLLER_0_NAME "/dev/epcs_flash_controller_0"
#define EPCS_FLASH_CONTROLLER_0_REGISTER_OFFSET 1024
#define EPCS_FLASH_CONTROLLER_0_SPAN 2048
#define EPCS_FLASH_CONTROLLER_0_TYPE "altera_avalon_epcs_flash_controller"


/*
 * eth_tse_0 configuration
 *
 */

#define ALT_MODULE_CLASS_eth_tse_0 altera_eth_tse
#define ETH_TSE_0_BASE 0x22800
#define ETH_TSE_0_ENABLE_MACLITE 0
#define ETH_TSE_0_FIFO_WIDTH 32
#define ETH_TSE_0_IRQ -1
#define ETH_TSE_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ETH_TSE_0_IS_MULTICHANNEL_MAC 0
#define ETH_TSE_0_MACLITE_GIGE 0
#define ETH_TSE_0_MDIO_SHARED 0
#define ETH_TSE_0_NAME "/dev/eth_tse_0"
#define ETH_TSE_0_NUMBER_OF_CHANNEL 1
#define ETH_TSE_0_NUMBER_OF_MAC_MDIO_SHARED 1
#define ETH_TSE_0_PCS 0
#define ETH_TSE_0_PCS_ID 0
#define ETH_TSE_0_PCS_SGMII 0
#define ETH_TSE_0_RECEIVE_FIFO_DEPTH 512
#define ETH_TSE_0_REGISTER_SHARED 0
#define ETH_TSE_0_RGMII 1
#define ETH_TSE_0_SPAN 1024
#define ETH_TSE_0_TRANSMIT_FIFO_DEPTH 1024
#define ETH_TSE_0_TYPE "altera_eth_tse"
#define ETH_TSE_0_USE_MDIO 1


/*
 * fifo_cmd_0_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_cmd_0_in altera_avalon_fifo
#define FIFO_CMD_0_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_CMD_0_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_CMD_0_IN_BASE 0x22db0
#define FIFO_CMD_0_IN_BITS_PER_SYMBOL 32
#define FIFO_CMD_0_IN_CHANNEL_WIDTH 0
#define FIFO_CMD_0_IN_ERROR_WIDTH 0
#define FIFO_CMD_0_IN_FIFO_DEPTH 16
#define FIFO_CMD_0_IN_IRQ -1
#define FIFO_CMD_0_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_CMD_0_IN_NAME "/dev/fifo_cmd_0_in"
#define FIFO_CMD_0_IN_SINGLE_CLOCK_MODE 0
#define FIFO_CMD_0_IN_SPAN 8
#define FIFO_CMD_0_IN_SYMBOLS_PER_BEAT 1
#define FIFO_CMD_0_IN_TYPE "altera_avalon_fifo"
#define FIFO_CMD_0_IN_USE_AVALONMM_READ_SLAVE 0
#define FIFO_CMD_0_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_CMD_0_IN_USE_AVALONST_SINK 0
#define FIFO_CMD_0_IN_USE_AVALONST_SOURCE 1
#define FIFO_CMD_0_IN_USE_BACKPRESSURE 1
#define FIFO_CMD_0_IN_USE_IRQ 1
#define FIFO_CMD_0_IN_USE_PACKET 0
#define FIFO_CMD_0_IN_USE_READ_CONTROL 0
#define FIFO_CMD_0_IN_USE_REGISTER 1
#define FIFO_CMD_0_IN_USE_WRITE_CONTROL 1


/*
 * fifo_cmd_0_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_cmd_0_in_csr altera_avalon_fifo
#define FIFO_CMD_0_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_CMD_0_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_CMD_0_IN_CSR_BASE 0x22d60
#define FIFO_CMD_0_IN_CSR_BITS_PER_SYMBOL 32
#define FIFO_CMD_0_IN_CSR_CHANNEL_WIDTH 0
#define FIFO_CMD_0_IN_CSR_ERROR_WIDTH 0
#define FIFO_CMD_0_IN_CSR_FIFO_DEPTH 16
#define FIFO_CMD_0_IN_CSR_IRQ 3
#define FIFO_CMD_0_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define FIFO_CMD_0_IN_CSR_NAME "/dev/fifo_cmd_0_in_csr"
#define FIFO_CMD_0_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_CMD_0_IN_CSR_SPAN 32
#define FIFO_CMD_0_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_CMD_0_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_CMD_0_IN_CSR_USE_AVALONMM_READ_SLAVE 0
#define FIFO_CMD_0_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_CMD_0_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_CMD_0_IN_CSR_USE_AVALONST_SOURCE 1
#define FIFO_CMD_0_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_CMD_0_IN_CSR_USE_IRQ 1
#define FIFO_CMD_0_IN_CSR_USE_PACKET 0
#define FIFO_CMD_0_IN_CSR_USE_READ_CONTROL 0
#define FIFO_CMD_0_IN_CSR_USE_REGISTER 1
#define FIFO_CMD_0_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_cmd_1_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_cmd_1_in altera_avalon_fifo
#define FIFO_CMD_1_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_CMD_1_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_CMD_1_IN_BASE 0x22da8
#define FIFO_CMD_1_IN_BITS_PER_SYMBOL 32
#define FIFO_CMD_1_IN_CHANNEL_WIDTH 0
#define FIFO_CMD_1_IN_ERROR_WIDTH 0
#define FIFO_CMD_1_IN_FIFO_DEPTH 16
#define FIFO_CMD_1_IN_IRQ -1
#define FIFO_CMD_1_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_CMD_1_IN_NAME "/dev/fifo_cmd_1_in"
#define FIFO_CMD_1_IN_SINGLE_CLOCK_MODE 0
#define FIFO_CMD_1_IN_SPAN 8
#define FIFO_CMD_1_IN_SYMBOLS_PER_BEAT 1
#define FIFO_CMD_1_IN_TYPE "altera_avalon_fifo"
#define FIFO_CMD_1_IN_USE_AVALONMM_READ_SLAVE 0
#define FIFO_CMD_1_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_CMD_1_IN_USE_AVALONST_SINK 0
#define FIFO_CMD_1_IN_USE_AVALONST_SOURCE 1
#define FIFO_CMD_1_IN_USE_BACKPRESSURE 1
#define FIFO_CMD_1_IN_USE_IRQ 1
#define FIFO_CMD_1_IN_USE_PACKET 1
#define FIFO_CMD_1_IN_USE_READ_CONTROL 0
#define FIFO_CMD_1_IN_USE_REGISTER 1
#define FIFO_CMD_1_IN_USE_WRITE_CONTROL 1


/*
 * fifo_cmd_1_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_cmd_1_in_csr altera_avalon_fifo
#define FIFO_CMD_1_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_CMD_1_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_CMD_1_IN_CSR_BASE 0x22d20
#define FIFO_CMD_1_IN_CSR_BITS_PER_SYMBOL 32
#define FIFO_CMD_1_IN_CSR_CHANNEL_WIDTH 0
#define FIFO_CMD_1_IN_CSR_ERROR_WIDTH 0
#define FIFO_CMD_1_IN_CSR_FIFO_DEPTH 16
#define FIFO_CMD_1_IN_CSR_IRQ 7
#define FIFO_CMD_1_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define FIFO_CMD_1_IN_CSR_NAME "/dev/fifo_cmd_1_in_csr"
#define FIFO_CMD_1_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_CMD_1_IN_CSR_SPAN 32
#define FIFO_CMD_1_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_CMD_1_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_CMD_1_IN_CSR_USE_AVALONMM_READ_SLAVE 0
#define FIFO_CMD_1_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_CMD_1_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_CMD_1_IN_CSR_USE_AVALONST_SOURCE 1
#define FIFO_CMD_1_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_CMD_1_IN_CSR_USE_IRQ 1
#define FIFO_CMD_1_IN_CSR_USE_PACKET 1
#define FIFO_CMD_1_IN_CSR_USE_READ_CONTROL 0
#define FIFO_CMD_1_IN_CSR_USE_REGISTER 1
#define FIFO_CMD_1_IN_CSR_USE_WRITE_CONTROL 1


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK TIMER_MAIN
#define ALT_TIMESTAMP_CLK TIMER_MAIN


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x22db8
#define JTAG_UART_0_IRQ 0
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * onchip_memory2_0 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2_0 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_BASE 0x10000
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "nios_test_onchip_memory2_0"
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_0_IRQ -1
#define ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 1
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65535
#define ONCHIP_MEMORY2_0_SPAN 65535
#define ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * onchip_memory2_0 configuration as viewed by sgdma_data_0_m_write
 *
 */

#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_BASE 0x10000
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_DUAL_PORT 0
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "nios_test_onchip_memory2_0"
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_IRQ -1
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 1
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_SIZE_VALUE 65535
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_SPAN 65535
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_DATA_0_M_WRITE_ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * onchip_memory2_0 configuration as viewed by sgdma_data_1_m_write
 *
 */

#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_BASE 0x10000
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_DUAL_PORT 0
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "nios_test_onchip_memory2_0"
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_IRQ -1
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 1
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_SIZE_VALUE 65535
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_SPAN 65535
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_DATA_1_M_WRITE_ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * onchip_memory2_0 configuration as viewed by sgdma_rx_m_write
 *
 */

#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_BASE 0x10000
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_DUAL_PORT 0
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "nios_test_onchip_memory2_0"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_IRQ -1
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 1
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_SIZE_VALUE 65535
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_SPAN 65535
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * onchip_memory2_0 configuration as viewed by sgdma_tx_m_read
 *
 */

#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_BASE 0x10000
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_DUAL_PORT 0
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "nios_test_onchip_memory2_0"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_IRQ -1
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 1
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_SIZE_VALUE 65535
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_SPAN 65535
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * pio_ext_sync configuration
 *
 */

#define ALT_MODULE_CLASS_pio_ext_sync altera_avalon_pio
#define PIO_EXT_SYNC_BASE 0x22d80
#define PIO_EXT_SYNC_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_EXT_SYNC_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_EXT_SYNC_CAPTURE 1
#define PIO_EXT_SYNC_DATA_WIDTH 32
#define PIO_EXT_SYNC_DO_TEST_BENCH_WIRING 1
#define PIO_EXT_SYNC_DRIVEN_SIM_VALUE 0
#define PIO_EXT_SYNC_EDGE_TYPE "ANY"
#define PIO_EXT_SYNC_FREQ 75000000
#define PIO_EXT_SYNC_HAS_IN 1
#define PIO_EXT_SYNC_HAS_OUT 0
#define PIO_EXT_SYNC_HAS_TRI 0
#define PIO_EXT_SYNC_IRQ 9
#define PIO_EXT_SYNC_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PIO_EXT_SYNC_IRQ_TYPE "EDGE"
#define PIO_EXT_SYNC_NAME "/dev/pio_ext_sync"
#define PIO_EXT_SYNC_RESET_VALUE 0
#define PIO_EXT_SYNC_SPAN 16
#define PIO_EXT_SYNC_TYPE "altera_avalon_pio"


/*
 * pio_led configuration
 *
 */

#define ALT_MODULE_CLASS_pio_led altera_avalon_pio
#define PIO_LED_BASE 0x22d90
#define PIO_LED_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_LED_CAPTURE 0
#define PIO_LED_DATA_WIDTH 8
#define PIO_LED_DO_TEST_BENCH_WIRING 0
#define PIO_LED_DRIVEN_SIM_VALUE 0
#define PIO_LED_EDGE_TYPE "NONE"
#define PIO_LED_FREQ 75000000
#define PIO_LED_HAS_IN 0
#define PIO_LED_HAS_OUT 1
#define PIO_LED_HAS_TRI 0
#define PIO_LED_IRQ -1
#define PIO_LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_LED_IRQ_TYPE "NONE"
#define PIO_LED_NAME "/dev/pio_led"
#define PIO_LED_RESET_VALUE 0
#define PIO_LED_SPAN 16
#define PIO_LED_TYPE "altera_avalon_pio"


/*
 * sgdma_data_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_data_0 altera_avalon_sgdma
#define SGDMA_DATA_0_ADDRESS_WIDTH 32
#define SGDMA_DATA_0_ALWAYS_DO_MAX_BURST 1
#define SGDMA_DATA_0_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_DATA_0_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_DATA_0_BASE 0x22cc0
#define SGDMA_DATA_0_BURST_DATA_WIDTH 8
#define SGDMA_DATA_0_BURST_TRANSFER 0
#define SGDMA_DATA_0_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_DATA_0_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_DATA_0_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_DATA_0_CONTROL_DATA_WIDTH 8
#define SGDMA_DATA_0_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_DATA_0_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_DATA_0_DESCRIPTOR_READ_BURST 0
#define SGDMA_DATA_0_DESC_DATA_WIDTH 32
#define SGDMA_DATA_0_HAS_READ_BLOCK 0
#define SGDMA_DATA_0_HAS_WRITE_BLOCK 1
#define SGDMA_DATA_0_IN_ERROR_WIDTH 0
#define SGDMA_DATA_0_IRQ 4
#define SGDMA_DATA_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_DATA_0_NAME "/dev/sgdma_data_0"
#define SGDMA_DATA_0_OUT_ERROR_WIDTH 0
#define SGDMA_DATA_0_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_DATA_0_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_DATA_0_SPAN 64
#define SGDMA_DATA_0_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_DATA_0_STREAM_DATA_WIDTH 32
#define SGDMA_DATA_0_SYMBOLS_PER_BEAT 4
#define SGDMA_DATA_0_TYPE "altera_avalon_sgdma"
#define SGDMA_DATA_0_UNALIGNED_TRANSFER 0
#define SGDMA_DATA_0_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_DATA_0_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_data_1 configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_data_1 altera_avalon_sgdma
#define SGDMA_DATA_1_ADDRESS_WIDTH 32
#define SGDMA_DATA_1_ALWAYS_DO_MAX_BURST 1
#define SGDMA_DATA_1_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_DATA_1_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_DATA_1_BASE 0x22c00
#define SGDMA_DATA_1_BURST_DATA_WIDTH 8
#define SGDMA_DATA_1_BURST_TRANSFER 0
#define SGDMA_DATA_1_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_DATA_1_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_DATA_1_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_DATA_1_CONTROL_DATA_WIDTH 8
#define SGDMA_DATA_1_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_DATA_1_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_DATA_1_DESCRIPTOR_READ_BURST 0
#define SGDMA_DATA_1_DESC_DATA_WIDTH 32
#define SGDMA_DATA_1_HAS_READ_BLOCK 0
#define SGDMA_DATA_1_HAS_WRITE_BLOCK 1
#define SGDMA_DATA_1_IN_ERROR_WIDTH 0
#define SGDMA_DATA_1_IRQ 8
#define SGDMA_DATA_1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_DATA_1_NAME "/dev/sgdma_data_1"
#define SGDMA_DATA_1_OUT_ERROR_WIDTH 0
#define SGDMA_DATA_1_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_DATA_1_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_DATA_1_SPAN 64
#define SGDMA_DATA_1_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_DATA_1_STREAM_DATA_WIDTH 32
#define SGDMA_DATA_1_SYMBOLS_PER_BEAT 4
#define SGDMA_DATA_1_TYPE "altera_avalon_sgdma"
#define SGDMA_DATA_1_UNALIGNED_TRANSFER 0
#define SGDMA_DATA_1_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_DATA_1_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_rx configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_rx altera_avalon_sgdma
#define SGDMA_RX_ADDRESS_WIDTH 32
#define SGDMA_RX_ALWAYS_DO_MAX_BURST 1
#define SGDMA_RX_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_RX_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_RX_BASE 0x22c80
#define SGDMA_RX_BURST_DATA_WIDTH 8
#define SGDMA_RX_BURST_TRANSFER 0
#define SGDMA_RX_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_RX_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_RX_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_RX_CONTROL_DATA_WIDTH 8
#define SGDMA_RX_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_RX_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_RX_DESCRIPTOR_READ_BURST 0
#define SGDMA_RX_DESC_DATA_WIDTH 32
#define SGDMA_RX_HAS_READ_BLOCK 0
#define SGDMA_RX_HAS_WRITE_BLOCK 1
#define SGDMA_RX_IN_ERROR_WIDTH 6
#define SGDMA_RX_IRQ 5
#define SGDMA_RX_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_RX_NAME "/dev/sgdma_rx"
#define SGDMA_RX_OUT_ERROR_WIDTH 0
#define SGDMA_RX_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_RX_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_RX_SPAN 64
#define SGDMA_RX_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_RX_STREAM_DATA_WIDTH 32
#define SGDMA_RX_SYMBOLS_PER_BEAT 4
#define SGDMA_RX_TYPE "altera_avalon_sgdma"
#define SGDMA_RX_UNALIGNED_TRANSFER 0
#define SGDMA_RX_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_RX_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_tx configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_tx altera_avalon_sgdma
#define SGDMA_TX_ADDRESS_WIDTH 32
#define SGDMA_TX_ALWAYS_DO_MAX_BURST 1
#define SGDMA_TX_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_TX_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_TX_BASE 0x22c40
#define SGDMA_TX_BURST_DATA_WIDTH 8
#define SGDMA_TX_BURST_TRANSFER 0
#define SGDMA_TX_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_TX_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_TX_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_TX_CONTROL_DATA_WIDTH 8
#define SGDMA_TX_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_TX_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_TX_DESCRIPTOR_READ_BURST 0
#define SGDMA_TX_DESC_DATA_WIDTH 32
#define SGDMA_TX_HAS_READ_BLOCK 1
#define SGDMA_TX_HAS_WRITE_BLOCK 0
#define SGDMA_TX_IN_ERROR_WIDTH 0
#define SGDMA_TX_IRQ 6
#define SGDMA_TX_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_TX_NAME "/dev/sgdma_tx"
#define SGDMA_TX_OUT_ERROR_WIDTH 1
#define SGDMA_TX_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_TX_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_TX_SPAN 64
#define SGDMA_TX_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_TX_STREAM_DATA_WIDTH 32
#define SGDMA_TX_SYMBOLS_PER_BEAT 4
#define SGDMA_TX_TYPE "altera_avalon_sgdma"
#define SGDMA_TX_UNALIGNED_TRANSFER 0
#define SGDMA_TX_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_TX_WRITE_BURSTCOUNT_WIDTH 4


/*
 * timer_main configuration
 *
 */

#define ALT_MODULE_CLASS_timer_main altera_avalon_timer
#define TIMER_MAIN_ALWAYS_RUN 0
#define TIMER_MAIN_BASE 0x22d40
#define TIMER_MAIN_COUNTER_SIZE 32
#define TIMER_MAIN_FIXED_PERIOD 0
#define TIMER_MAIN_FREQ 75000000
#define TIMER_MAIN_IRQ 2
#define TIMER_MAIN_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_MAIN_LOAD_VALUE 74999
#define TIMER_MAIN_MULT 0.0010
#define TIMER_MAIN_NAME "/dev/timer_main"
#define TIMER_MAIN_PERIOD 1
#define TIMER_MAIN_PERIOD_UNITS "ms"
#define TIMER_MAIN_RESET_OUTPUT 0
#define TIMER_MAIN_SNAPSHOT 1
#define TIMER_MAIN_SPAN 32
#define TIMER_MAIN_TICKS_PER_SEC 1000.0
#define TIMER_MAIN_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_MAIN_TYPE "altera_avalon_timer"


/*
 * uart_keyb configuration
 *
 */

#define ALT_MODULE_CLASS_uart_keyb altera_avalon_uart
#define UART_KEYB_BASE 0x22d00
#define UART_KEYB_BAUD 9600
#define UART_KEYB_DATA_BITS 8
#define UART_KEYB_FIXED_BAUD 1
#define UART_KEYB_FREQ 75000000
#define UART_KEYB_IRQ 10
#define UART_KEYB_IRQ_INTERRUPT_CONTROLLER_ID 0
#define UART_KEYB_NAME "/dev/uart_keyb"
#define UART_KEYB_PARITY 'N'
#define UART_KEYB_SIM_CHAR_STREAM ""
#define UART_KEYB_SIM_TRUE_BAUD 0
#define UART_KEYB_SPAN 32
#define UART_KEYB_STOP_BITS 1
#define UART_KEYB_SYNC_REG_DEPTH 2
#define UART_KEYB_TYPE "altera_avalon_uart"
#define UART_KEYB_USE_CTS_RTS 0
#define UART_KEYB_USE_EOP_REGISTER 0

#endif /* __SYSTEM_H_ */
